WebClient/TweetSumm_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search_engine.urls')),
]

WebClient/search_engine/urls.py
from django.urls import path
from . import views

app_name='search_engine'
urlpatterns = [
    path('', views.home, name='home' ),
    path('search',views.Search.as_view(), name='search')
]

WebClient/search_engine/models.py
from django.db import models

# Create your models here.

WebClient/search_engine/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage
# Create your views here.
from . import datePicker
from . import apiConsumer
import json
from django.utils.safestring import mark_safe
from django.template.loader import render_to_string
from datetime import datetime
import dateutil.parser
from django.views import View
import ast,sys

response_saved=None
paginator=None
class Search(View):

    def post(self,request):
        global response_saved, paginator

        form=datePicker.Form()
        if 'search' in request.POST:
            paginator=None
            response_saved=None
            q=request.POST['search']
            date=request.POST['date']
            date_parts=date.split('/')
            date=f"{date_parts[2]}-{date_parts[1]}-{date_parts[0]}"
            if not q.strip():
                context={
                    'placeholder_query':q,
                    'no_tweet': 1,
                    'error':  "Sorry! No available tweets",
                    'retrieved': 0,
                    'candidates': 0,
                    'form':form
                }
            else :
                response= apiConsumer.get_summarization(q,date)
                if response==400:
                    context={
                        'placeholder_query':q,
                        'no_tweet': 1,
                        'error': "Sorry! No available tweets",
                        'retrieved': 0,
                        'candidates': 0,
                        'form':form
                    }
                elif response==429:
                    context={
                        'placeholder_query':q,
                        'server': 1,
                        'error': "Ouie! Rate limite exceeded for this ressource",
                        'retrieved': 0,
                        'candidates': 0,
                        'form':form
                    }
                elif response==500:
                    context={
                        'placeholder_query':q,
                        'server': 1,
                        'error': "Oops! Couldn't reach server",
                        'retrieved': 0,
                        'candidates': 0,
                        'form':form
                    }
                else:
                    tweets_all=response['summary']
                    if len(tweets_all)==0:
                        context={
                        'placeholder_query':q,
                        'no_tweet': 1,
                        'error': "Sorry! No available tweets",
                        'retrieved': 0,
                        'candidates': 0,
                        'form':form
                        }
                    else:
                        
                        for t in tweets_all:
                            dt=dateutil.parser.parse(t['created_at'])
                            t['created_at']=datetime.strftime(dt,'%I:%M%p - %d %b %Y')
                            #t['user'] = ast.literal_eval(t['user'])
                            #print( type(t['user']),file=sys.stderr)
                        paginator = Paginator(tweets_all, 5) # Show 5 tweets per page
                        page = request.GET.get('page')
                        try:
                            tweets = paginator.get_page(page)
                        except PageNotAnInteger:
                            tweets = paginator.get_page(1)
                        except EmptyPage:
                            tweets = paginator.get_page(paginator.num_pages)
                            
                        candidates_stat= float(response['candidates'])/float(response['retrieved'])*100
                        summary_stat= len(tweets_all)/float(response['retrieved'])*100
                        response_saved={'retrieved':response['retrieved'],'candidates': response['candidates'],
                                        'candidates_stat': candidates_stat,'summary_stat':summary_stat,
                                        'summary':len(tweets_all),'q':q}
                        context = {
                            'placeholder_query':q,
                            #'all_t': k,
                            'tweets': tweets,
                            'retrieved': response['retrieved'],
                            'candidates': response['candidates'],
                            'candidates_stat': candidates_stat,
                            'summary_stat':summary_stat,
                            'summary':len(response['summary']),
                            'form':form,
                            'js_data': json.dumps(q)
                        }           
            return render(request,'search_engine/search.html',context)
        '''
        elif request.is_ajax():
            print('hi')
            page = request.GET.get('page')
            print(request.GET.get('t'))
            paginator = paginator(request.GET.get('t'), 5)
            try:
                tweets = paginator.get_page(page)
            except PageNotAnInteger:
                tweets = paginator.get_page(1)
            except EmptyPage:
                tweets = paginator.get_page(paginator.num_pages)        
            context = {
                        'placeholder_query': request.GET.get['q'],
                        'tweets': tweets,
                        'retrieved': request.GET.get['retrieved'],
                        'candidates': request.GET.get['candidates'],
                        #'candidates_stat': response_saved['candidates_stat'],
                        #'summary_stat':response_saved['summary_stat'],
                        'summary': request.GET.get['summary'],
                        'form':datePicker.Form()
                    }
            html = render_to_string('search_engine/search.html',context)
            return HttpResponse(html)
        '''
        return render(request, 'base.html',{'form':form})
    def get(self,request):
        if ('page' in request.GET and response_saved is not None):
            page = request.GET.get('page')
            try:
                tweets = paginator.get_page(page)
            except PageNotAnInteger:
                tweets = paginator.get_page(1)
            except EmptyPage:
                tweets = paginator.get_page(paginator.num_pages)        
            context = {
                        'placeholder_query': response_saved['q'],
                        'tweets': tweets,
                        'retrieved': response_saved['retrieved'],
                        'candidates': response_saved['candidates'],
                        'candidates_stat': response_saved['candidates_stat'],
                        'summary_stat':response_saved['summary_stat'],
                        'summary': response_saved['summary'],
                        'form':datePicker.Form()
                    }
            return render(request,'search_engine/search.html',context)
        return render(request, 'base.html',{'form':datePicker.Form()})


def home(request): 
    form=datePicker.Form()
    return render(request, 'base.html',{'form':form})

WebClient/search_engine/templates/search_engine/dateInput.html
<div class="form-group datePicker col-10" >
    {% include "bootstrap_datepicker_plus/input.html" %}
</div>

<script>
$( "label" ).remove();
</script>

WebClient/search_engine/templates/search_engine/search.html
{% extends 'base.html' %}
{% load fontawesome %}
{% load static %}

{% block content %}
{% if tweets %}
<div class='container-fluid py-3' id='container_search'>
    <div class='row'>
        <div class='col-xl-3 col-lg-12 col-md-12 col-sm-12 m-3' >
            <div classe="row w-100 ">
                <div class='col p-1 ' >
                    <div class="card statsCard border-0">
                        <div class="card-body">
                            <span class="float-right cardFont">{% fontawesome_icon 'download' color='#E9ECEF' large=True %}</span>
                            <h5 class="card-title">Retrieved from Twitter</h5>
                            <h6 class="card-subtitle mb-2 text-muted"> {{retrieved}} tweets</h6>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--
                 <div class='col p-1' >
                    <div class="card  statsCard border-0">
                        <div class="card-body">
                            <span class="float-right cardFont">{% fontawesome_icon 'filter' color='#E9ECEF' large=True %}</span>
                            <h5 class="card-title">Trash filtered</h5>
                            <h6 class="card-subtitle mb-2 text-muted"> {{candidates}} tweets</h6>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: {{candidates_stat}}%" aria-valuenow="{{candidates_stat}}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
                -->
                 <div class='col p-1' >
                    <div class="card  statsCard border-0">
                        <div class="card-body">
                            <span class="float-right cardFont">{% fontawesome_icon 'compress' color='#E9ECEF' large=True %}</span>
                            <h5 class="card-title">Summary</h5>
                            <h6 class="card-subtitle mb-2 text-muted"> {{summary}} tweets</h6>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width: {{summary_stat}}%" aria-valuenow="{{summary_stat}}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='col-xl-6 col-lg-12 col-md-12 col-sm-12 m-3' >
            <div class="card w-100" id="tweets">
                <ul class="list-group list-group-flush">
                    {% for tweet in tweets %}
                        <li class="list-group-item">
                            <div class='container w-100'>
                                <div class="row w-100">
                                    <div class="col-12 ">
                                        <div class="float-left">
                                            <img src="{{tweet.user.profile_image_url_https}}" alt="user profile image" class="img-thumbnail rounded-circle">
                                        </div>
                                        <a href="https://twitter.com/statuses/{{tweet.id_str}}"  target="_blank" class="float-right link_tweet" >{% fontawesome_icon 'twitter' color='#1DA1F2' large=True %}</a>
                                        <div class="d-inline">
                                            <div class="d-block m-1">
                                                <h5 class="mb-0 ml-2 d-inline">{{tweet.user.name}}</h5>
                                                <span class="timePub text-muted">. {{tweet.created_at}}</span>
                                                <a href="https://twitter.com/{{tweet.user.screen_name}}" target="_blank" class="d-block user_name"> @{{tweet.user.screen_name}}</a>
                                            </div>
                                        </div>
                                        <p class="my-2 tweet_text">{{tweet.text}}</p>
                                        
                                        <span class="badge badge-light mr-3"> {% fontawesome_icon 'retweet' large=True %} {{tweet.retweet_count}}</span>
                                        <span class="badge badge-light mr-3"> {% fontawesome_icon 'star' large=True %} {{tweet.score|floatformat:4}}</span>
                                        <span class="badge badge-light"> {% fontawesome_icon 'tag' large=True %} {{tweet.label}}</span>
                                        
                                    </div>
                                </div>
                            </div>      
                        </li>
                    {% empty %}
                        <p>No tweets are available.</p>
                    {% endfor %}
                </ul>
            </div>


            <div class="pagination">
                <span class="step-links">
                    {% if tweets.has_previous %}
                        <a id='first_page' v=1 href="?page=1">&laquo; first</a>
                        <a id='prev_page' href="?page={{ tweets.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ tweets.number }} of {{ tweets.paginator.num_pages }}.
                    </span>

                    {% if tweets.has_next %}
                        <a id='next_page' href="?page={{ tweets.next_page_number }}">next</a>
                        <a id='last_page' href="?page={{ tweets.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
            
        </div>
    </div>
</div>
{% else %}
            {% if no_tweet %}
                <div class='text-center p-2 m-4'>
                    <img id='error_img' src={% static "media/no_tweet.png" %} class="img-fluid p-2" alt="Responsive image">
                    <div class='container'>
                    <div class='row'>
                        <div class='col-12' >
                        <div id='error_text'>
                            <h1> {{error}} </h1>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
            {% else %}
                 <div class='text-center p-2 m-4'>
                    <img id='error_img' src={% static "media/icons8-serveur-100.png" %} class="img-fluid p-2" alt="Responsive image">
                    <div class='container'>
                    <div class='row'>
                        <div class='col-12' >
                        <div id='error_text'>
                            <h1> {{error}} </h1>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
            {% endif %}
{% endif %}



{% endblock content %}
<!--
{% block javascript %}
  <script>
  $(function() { 
      $.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
});
       
        let a={{all_t}}
       

        let q="{{placeholder_query}}"
        let retrieved={{retrieved}}
        let candidates={{candidates}}
        let candidates_stat={{candidates_stat}}
        let summary_stat={{summary_stat}}
        let summary={{summary}}
        let page=1
        console.log(a)
        $("#next_page").click(function () {   
             $.ajax({
                type: 'POST',
                url: '{% url 'search_engine:search' %}',
                data: {
                    't': a,
                    'page':page,
                    'q': q,
                    'retrieved': retrieved,
                    'candidates': candidates,
                    'candidates_stat': candidates_stat,
                    'summary_stat':summary_stat,
                    'summary':summary,
                },
                dataType: 'json',
                success: function (data) {
                    $('html').replaceWith(data)
                }
            });
        });
    });
  </script>

{% endblock %}
-->

WebClient/templates/base.html
<!DOCTYPE html>
<html>
{% load fontawesome %}
<head>
  <meta charset="utf-8">
  <title> Tweet Summarization</title>
  <meta name="author" content="Lila BOUALILI">
  <meta name="description" content="Tweet Summarization proto">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    
  <!--Links-->
  {% load static %}
  <link rel="icon" href="{% static 'media/favicon.ico' %}" type="image/x-icon"/>
  <!-- Bootstrap CSS  CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
        crossorigin="anonymous">
  <!--Custom styles-->
  <link rel="stylesheet" type="text/css" href="{% static 'styles/style.css' %}">
  <!--Links-->
  {% load bootstrap4 %}          {# Embed Bootstrap CSS #}
  {% bootstrap_javascript jquery='full' %} 
  {% fontawesome_stylesheet %}
  {{ form.media }}
</head>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-light shadow sticky-top py-2 d-flex navCustom bg-ligh">
    <div class='container my-1 d-flex justify-content-center'>
      <div class="row d-flex justify-content-center">
        <div class="col-xl-6 col-md-11 col-xs-11">
     
          <form class="form-inline d-flex justify-content-center" action="{% url 'search_engine:search' %}" method="post" id='summarize_form'>
            {% csrf_token %}
            <div class="row clearfix py-1 my-0 search_form">
              <div class="col-lg-5 col-md-12 col-sm-12 form-group py-1 my-0 d-flex justify-content-center">
                {% fontawesome_icon 'search' color='#868E96' %}
                 <input class="form-control col-10  border-0 input" 
                  type="search" 
                  placeholder="Search"
                  {% if placeholder_query %}
                  value="{{placeholder_query}}"
                  {% endif %}
                  aria-label="Search"
                  id='query_search'
                  name='search' required>
              </div>
              <div class="col-lg-4 col-md-12 col-sm-12 form-group py-1 my-0 d-flex justify-content-center">
                {% fontawesome_icon 'calendar' color='#868E96' %}
                {{form}}
              </div>
              <div class="col-lg-3 col-md-12 d-flex justify-content-center div_summarize">
                  <button class="btn btn-primary col-12" id="summarize" type="submit" >
                    Summarize
                  </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    
  </nav> 

  <div id='content'>
    {% block content%} 
    <img id='placeholder-img' src="{% static 'media/black_twitter.jpg' %}" class="img-fluid" alt="Responsive image">
    <div class='container'>
      <div class='row'>
        <div class='col-12' >
          <div id='placeholder'>
            <h1> See what happend on Twitter Last week </h1>
            <h3> Choose your start day and summarize tweets around the subject you want </h3>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </div>
  <div class='container text-center' id="Description-container">
      <div class="row" id='Description-title'>
        <div class="col-12 text-center ">
         <h1>Tweet Summarization Engine!</h1>
         <h3>Get efficiently the information you need</h3>
        </div>
      </div>
      <div class="row">
          <div class="col-lg-6 px-5">
            <div class="rounded-circle bg-primary-light">
              {% fontawesome_icon 'bolt' large=True %}
            </div>
            <h2 class='my-3'>Relevant tweets</h2>
            <p> Tweet Summarization Engine selects only the most relevant tweets to your search query. 
                No more searching for your topic of interest among a ton of others that do not interest you.</p>
         </div><!-- /.col-lg-4 -->
         <div class="col-lg-6 px-5">
            <div class="rounded-circle bg-primary-light">
              {% fontawesome_icon 'copy ' large=True %}
            </div>
             <h2 class='my-3'>No Redundancy</h2>
            <p>Tweet Summarization selects novel tweets and remove all redudant ones. 
                No more reading the same information in dozens of duplicated tweets.</p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
  </div>
  <!--Footer-->
  <footer class="page-footer font-small " id='footer-container'>
    <!-- Footer Links -->
    <div class="container-fluid text-center  footer-links text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 col-sm-12 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase">Tweet Sumarization Project</h5>
          <p> Project developped by Lila BOUALILI in the context of her last year project at the Highest National School of Computer Science of Algiers (ESI ex. INI). 
          Project proposed by Pr. Mohand BOUGHANEM of IRIT-University of Paul Sabatier, Toulouse. 
          Supervised by Pr. M.BOUGHANEM (IRIT) & Dr.L SAID LHADJ (ESI).
          </p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 colsm-0 mb-md-0 mb-3">
        </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-sm-12 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!">Source code</a>
              </li>
              <li>
                <a href="http://esi.dz/" target="_blank" rel="noopener noreferrer">ESI</a>
              </li>
              <li>
                <a href="https://www.irit.fr/" target="_blank" rel="noopener noreferrer">IRIT</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright
    <!--
      <a href="https://aach/"> qqch.com</a>
    -->
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

  <div class="spinner-border text-dark d-none" role="status">
          <span class="sr-only">Loading...</span>
  </div>

  <!--Scripts-->
  <!-- jQuery CDN -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <!-- Popper CDN -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
          crossorigin="anonymous"></script>
  <!-- jQuery local fallback -->
  <script>window.jQuery || document.write('<script src="{% static 'scripts/jquery.min.js' %}"><\/script>')</script>  
  <!-- Bootstrap JS  CDN -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
          crossorigin="anonymous"></script>
  <!-- Bootstrap JS local fallback -->
  <script>window.jQuery.fn.modal || document.write('<script src="{% static 'scripts/bootstrap.min.js' %}"><\/script>')</script>
  <!-- Bootstrap CSS local fallback -->
  <div id="bootstrapCssTest" class="hidden"></div>
  <script>
    $(function() {
      if ($('#bootstrapCssTest').is(':visible')) {
        $("head").prepend('<link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">');
      }
    });

  </script>
  <script src="{% static 'scripts/linkify.min.js' %}"></script>
  <script src="{% static 'scripts/linkify-jquery.min.js' %}"></script> 
  <script src="{% static 'scripts/blockui.js' %}"></script> 
  <script>
  $(function() { 
    $('p.tweet_text').linkify({
        target: "_blank"
      });
    $('#summarize_form').on('submit', function() {
      $.blockUI({
        message: ' <div class="spinner-border text-primary m-3" id="spinner" role="status"><span class="sr-only">Loading...</span></div>',
        css: { backgroundColor: 'inherite', border:'0px'} 
      });
    });
  });
  </script>
  {% block javascript %}
  {% endblock %}
  <!--Scripts-->
</body>

</html>